name: Delete Old Workflow Runs
on:
  # 每周日 00:00 自动运行
  schedule:
    - cron: '0 0 * * 0'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0  # 不按天数保留
          keep_minimum_runs: 10  # 保留最近的5个运行记录
