name: Check and Update File from Gitee

on:
  schedule:
    # 北京时间每天8点运行（UTC 0点）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set Beijing Timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        echo "CURRENT TIME: $(date '+%Y-%m-%d %H:%M:%S')" >> update.log
        
    - name: Get current SHA
      id: get_sha
      run: |
        if [ -f "单线路.zip" ]; then
          sha=$(sha1sum 单线路.zip | awk '{print $1}')
          echo "current_sha=$sha" >> $GITHUB_OUTPUT
          echo "Local file SHA: $sha" >> update.log
        else
          echo "current_sha=" >> $GITHUB_OUTPUT
          echo "No local file found" >> update.log
        fi
        
    - name: Fetch file info from Gitee
      id: file_info
      run: |
        response=$(curl -s "https://gitee.com/api/v5/repos/PizazzXS/another-d/contents/%E5%8D%95%E7%BA%BF%E8%B7%AF.zip")
        sha=$(echo $response | jq -r '.sha')
        download_url=$(echo $response | jq -r '.download_url')
        echo "remote_sha=$sha" >> $GITHUB_OUTPUT
        echo "download_url=$download_url" >> $GITHUB_OUTPUT
        echo "Remote file SHA: $sha" >> update.log
        
    - name: Download if changed
      if: steps.get_sha.outputs.current_sha != steps.file_info.outputs.remote_sha
      run: |
        echo "Downloading new version at $(date '+%Y-%m-%d %H:%M:%S')..." >> update.log
        curl -L -o 单线路.zip "${{ steps.file_info.outputs.download_url }}"
        # 删除可能存在的旧解压文件（根据你的实际情况调整）
        rm -rf 解压后的目录/ || true
        
    - name: Unzip with overwrite
      if: steps.get_sha.outputs.current_sha != steps.file_info.outputs.remote_sha && success()
      run: |
        echo "Unzipping with overwrite at $(date '+%Y-%m-%d %H:%M:%S')..." >> update.log
        unzip -o 单线路.zip -d ./  # -o 表示覆盖已存在文件
        
    - name: Commit changes
      if: steps.get_sha.outputs.current_sha != steps.file_info.outputs.remote_sha && success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "自动更新: 单线路.zip [$(date '+%Y-%m-%d %H:%M:%S')]"
        git push
        
    - name: Upload log
      uses: actions/upload-artifact@v3
      with:
        name: update-log
        path: update.log
