name: Xiaosa Auto Updater

on:
  schedule:
    # 每天北京时间早上8点运行 (UTC 0点)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 获取所有分支历史，避免后续提交失败
        fetch-depth: 0  

    - name: Download zip file
      run: |
        # 下载zip文件到仓库根目录
        curl -L -o "单线路.zip" "https://gitee.com/PizazzXS/another-d/raw/master/单线路.zip"
        
    - name: Unzip and overwrite
      run: |
        # 解压并覆盖现有文件 (保留其他文件)
        unzip -O GB18030 -o "单线路.zip" -d .
        
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # 只添加被修改的文件，不影响其他文件
        git add "单线路.zip"
        git add -u .
        
        # 检查是否有实际变化
        if git diff-index --quiet HEAD --; then
          echo "没有检测到文件变化"
        else
          git commit -m "自动更新: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
